Regexp support
fuhrysteve/marshmallow-jsonschema pull request #72
Opened 2019-07-10 13:13 UTC by fuhrysteve

Resolves conflicts from #24

2019-07-22 22:02 UTC, atmo requested changes

2019-07-22 22:02 UTC, atmo commented on marshmallow_jsonschema/validation.py
> +    if not isinstance(field, fields.String):
I recommend raising an `UnsupportedValueError` here as I did for other validators. marshmallow will fail on non-strings anyway:
```python
>>> from marshmallow import fields
>>> from marshmallow.validate import Regexp
>>> f = fields.Integer(validate=Regexp(".*"))
>>> f.deserialize(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lynx/projects/marshmallow-jsonschema/.venv/lib/python3.7/site-packages/marshmallow/fields.py", line 301, in deserialize
    self._validate(output)
  File "/home/lynx/projects/marshmallow-jsonschema/.venv/lib/python3.7/site-packages/marshmallow/fields.py", line 224, in _validate
    r = validator(value)
  File "/home/lynx/projects/marshmallow-jsonschema/.venv/lib/python3.7/site-packages/marshmallow/validate.py", line 362, in __call__
    if self.regex.match(value) is None:
TypeError: expected string or bytes-like object
```
Custom fields have to be handled with care though as they are not required to be an instance of `fields.String`. Though they are not supported yet, there is an attempt in #22.

2019-07-22 22:02 UTC, atmo commented
Hi @fuhrysteve ! Could you please resolve the conflicts in this PR? It would be great to have it merged into master.

2026-04-19 18:12 UTC, fuhrysteve commented
Same as #24 — regexp validator support already in tree. Closing as superseded.

2026-04-19 18:12 UTC, closed without merging